language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer --verbose self-update
  - composer --version

install:
  - composer --verbose install

script:
  - "cd web && ./../vendor/bin/drush site-install --verbose --yes --db-url=sqlite://tmp/site.sqlite"
