language: php
php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

env:
  - SIMPLETEST_DB=sqlite://tmp/site.sqlite

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update
  - composer --version

install:
  - composer --verbose install

script:
  # Test stable release
  - cd $TRAVIS_BUILD_DIR/web
  - ./../vendor/bin/drush site-install --verbose --yes --db-url=sqlite://tmp/site.sqlite
  - ./../vendor/bin/drush runserver http://127.0.0.1:8080 &
  - sleep 3
  - export SIMPLETEST_BASE_URL="http://127.0.0.1:8080"
  # Skip core/tests/Drupal/Tests/ComposerIntegrationTest.php because web/ has no composer.json
  - ./../vendor/bin/phpunit -c core --exclude-group Composer
  - ./../vendor/bin/drush
  - ./../vendor/bin/drupal

  # Test dev release
  - cd $TRAVIS_BUILD_DIR
  - composer --verbose require --no-update drupal/core:8.0.x-dev
  - composer --verbose update
  - cd $TRAVIS_BUILD_DIR/web
  - ./../vendor/bin/drush site-install --verbose --yes --db-url=sqlite://tmp/site.sqlite
  # Skip core/tests/Drupal/Tests/ComposerIntegrationTest.php because web/ has no composer.json
  - ./../vendor/bin/drush runserver http://127.0.0.1:8081 &
  - sleep 3
  - export SIMPLETEST_BASE_URL="http://127.0.0.1:8081"
  - ./../vendor/bin/phpunit -c core --exclude-group Composer
  - ./../vendor/bin/drush
  - ./../vendor/bin/drupal
