language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer --verbose self-update
  - composer --version

install:
  - composer --verbose install

script:
  - cd web
  - ./../vendor/bin/drush site-install --verbose --yes --db-url=sqlite://tmp/site.sqlite"
  # Skip core/tests/Drupal/Tests/ComposerIntegrationTest.php because web/ has no composer.json
  - ./../vendor/bin/phpunit -c core --exclude-group Composer
